import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const exec = promisify(execFile);
await exec(process.execPath, ['scripts/build.mjs', '--check']);
const shell = await readFile(new URL('../src/coupon-pilot.shell.js', import.meta.url), 'utf8');
const built = await readFile(new URL('../coupon-pilot.user.js', import.meta.url), 'utf8');
const harrisTeeter = await readFile(new URL('../modules/harris-teeter.js', import.meta.url), 'utf8');
const lowesFoods = await readFile(new URL('../modules/lowes-foods.js', import.meta.url), 'utf8');
const walgreens = await readFile(new URL('../modules/walgreens.js', import.meta.url), 'utf8');
const manifest = await readFile(new URL('../modules/manifest.mjs', import.meta.url), 'utf8');
const metadataVersion = built.match(/^\/\/ @version\s+([^\s]+)$/m)?.[1];
const appVersion = shell.match(/const APP_VERSION\s*=\s*['"]([^'"]+)['"]/m)?.[1];
assert.equal(metadataVersion, appVersion, '@version and APP_VERSION must stay in sync');
assert.match(built, /GENERATED BASE SCRIPT/, 'distributable must be generated from the shell source');
assert.doesNotMatch(built, /registerWalgreensModule|registerHarrisTeeterModule/, 'standalone modules must not be bundled into the base userscript');
assert.match(built, /@match\s+\*:\/\/\*\/\*/, 'base userscript must be available for future module hosts');
assert.match(shell, /const MODULE_API_VERSION = 3/, 'shell module API version missing');
assert.match(shell, /discoverModuleItems/, 'runtime item contract validation is missing');
assert.match(shell, /VALID_ITEM_STATUSES/, 'module item states must be validated');
assert.match(shell, /parseModuleManifest/, 'local module manifest validation is missing');
assert.match(shell, /CouponPilot\.register exactly once/, 'module registration count must be enforced');
assert.match(shell, /INSTALLED_MODULES_KEY/, 'installed module storage is missing');
assert.match(shell, /installModuleFile/, 'local file module installation is missing');
assert.match(shell, /setModuleEnabled/, 'installed modules must be individually controllable');
assert.match(shell, /removeInstalledModule/, 'installed modules must be removable');
assert.match(shell, /Local modules are trusted JavaScript/, 'module trust warning is missing');
assert.match(shell, /typeof adapter\[key\] !== 'function'/, 'module functions must be type-checked');
assert.match(shell, /dryRun:\s*true/, 'fresh installs must default to Dry Run');
assert.match(shell, /new AbortController\(\)/, 'live runs must remain abortable');
assert.match(shell, /new MutationObserver\(/, 'lazy-loaded DOM changes must remain observable');
assert.match(shell, /return Boolean\(revealed\)/, 'load-more timeout must not report false progress');
assert.match(shell, /if \(actionCount\(\) >= maxActions\) break;/, 'max actions must be enforced within each discovered batch');
assert.match(shell, /const dryRun = Boolean\(state\.automation\.dryRun\)/, 'run mode must be fixed when a run starts');
assert.match(shell, /markPreview\(item\.element, 'blocked'/, 'blocked preview marks must be tracked for cleanup');
assert.ok(!shell.includes('row.innerHTML ='), 'retailer-controlled coupon text must not be interpolated into HTML');
assert.ok(!built.includes('globalThis'), 'installable userscript must pass Tampermonkey browser linting');
assert.match(shell, /tab\.onclick = selectRuleTab/, 'tab handlers must not declare functions inside a loop');
assert.match(shell, /GM_setClipboard/, 'copyable debug reports must remain available');
assert.match(shell, /ambiguousSamples/, 'debug reports must include ambiguous control samples');
assert.match(shell, /installedModules:/, 'debug reports must include installed module metadata');
const debugReportSource = shell.slice(shell.indexOf('function createDebugReport'), shell.indexOf('async function copyDebugReport'));
assert.doesNotMatch(debugReportSource, /fileName/, 'debug reports must not expose local module filenames');
assert.doesNotMatch(debugReportSource, /title: item\.title/, 'debug reports must not expose coupon titles');
assert.match(shell, /typeof crypto === 'undefined' \|\| !crypto\.subtle/, 'digest fallback must work when crypto is unavailable');
assert.match(harrisTeeter, /const \{ apiVersion, ITEM_STATUS/, 'adapter API version and item states missing');
assert.match(harrisTeeter, /==CouponPilotModule==/, 'Harris Teeter installable module header missing');
assert.match(harrisTeeter, /CouponPilot\.register/, 'Harris Teeter standalone registration missing');
assert.match(harrisTeeter, /async verify\(/, 'adapter must verify actions');
assert.match(harrisTeeter, /healthCheck\(/, 'adapter must expose health check');
assert.match(harrisTeeter, /safeCouponIdentity/, 'stable fallback coupon identity is missing');
assert.match(harrisTeeter, /\^clip\(\?:\\s\+for\\s\+coupon:/, 'Harris Teeter accessible Clip labels must be recognized');
assert.match(harrisTeeter, /CouponCard-\(\.\+\)/, 'Harris Teeter card IDs must use the stable site identifier');
assert.ok(!harrisTeeter.includes('\\badd\\b'), 'generic Add matching is forbidden');
assert.match(walgreens, /coupon-id/, 'Walgreens stable offer identity is missing');
assert.match(walgreens, /==CouponPilotModule==/, 'Walgreens installable module header missing');
assert.match(walgreens, /CouponPilot\.register/, 'Walgreens standalone registration missing');
assert.match(walgreens, /clip rebate/i, 'Walgreens rebate actions must be explicit');
assert.match(walgreens, /availableFilterActive/, 'Walgreens verification must remain scoped to the Available filter');
assert.ok(!walgreens.includes('\\bshop\\b'), 'generic Shop matching is forbidden');
assert.match(lowesFoods, /==CouponPilotModule==/, 'Lowes Foods installable module header missing');
assert.match(lowesFoods, /CouponPilot\.register/, 'Lowes Foods standalone registration missing');
assert.match(lowesFoods, /c-button--offer-clip/, 'Lowes Foods must use the dedicated offer control');
assert.match(lowesFoods, /offer-card__corner-icon--clipped/, 'Lowes Foods clipped-state marker is missing');
assert.match(lowesFoods, /c-card__link--offer/, 'Lowes Foods stable offer identity is missing');
assert.match(lowesFoods, /async verify\(/, 'Lowes Foods module must verify actions');
assert.ok(!lowesFoods.includes('\\badd\\b'), 'generic Add matching is forbidden for Lowes Foods');
for (const moduleFile of ['harris-teeter.js', 'lowes-foods.js', 'walgreens.js']) assert.match(manifest, new RegExp(`['"]${moduleFile.replace('.', '\\.')}['"]`), `${moduleFile} missing from module manifest`);
console.log('Coupon Pilot static safety checks passed.');
